version: '3'

services:
  apache:
    build:
      args:
        user: camondoni
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "teste123"
      MYSQL_DATABASE: "webjump"
    ports:
      - "3306:3306" 